// Don't ever do this at home kids! Just for demo purposes
window.facts = [
    "The sun is flinging 1 million tons of matter out into space every second?",
    "At the heart of the sun 600 million tonnes of hydrogen are converted into helium every second?",
    "Between four and five people are born every second - two people die every second?",
    "The sun loses up to a billion kilograms every second because of the solar wind that blasts out from its surface?",
    "The sun's energy production each second is enough to supply the electrical need of the U.S. for 50 million years at the current rate of consumption?",
    "Every three seconds, an area of the South American rain forest the size of a football field is cut down?",
    "Every second, a hurricane releases as much energy as the explosion of a Hiroshima-type atomic bomb?",
    "Lightning travels 90,000 miles a second — almost half the speed of light?",
    "Americans purchase an average of 100 cans of Campbell's Soup every second of every day in the month of January?",
    "At least 100,000 different chemical reactions occur in the normal human brain every second?",
    "Every person has nearly 400,000 radioactive atoms disintegrating into other atoms in his or her body each second?",
    "Twenty-four frames per second are projected in most animated films?",
    "No high jumper has ever been able to stay off the ground for more than one second?",
    "The ruby-throated hummingbird beats its wings at the incredibly rapid speed of 50 to 70 times a second. ",
    "A cheetah can advance 7 to 8 meters in a single stride, and the animal completes four strides per second?",
    "Alligators and old people have something in common, at least auditorily. They can hear notes only up to 4,000 vibrations a second?",
    "The average minimal speed of birds in order to remain aloft in flight is reported to be about 5 meters per second?",
    "Cats purr at 26 cycles per second, the same as an idling diesel engine?",
    "One hundred thousand cubic feet of water pours over the Niagara Falls every second?",
    "A bumble bee flaps its wings 160 beats per second?",
    "A dragonfly flaps its wings 20 to 40 times a second?",
    "Bees and houseflies flap their wings 200 times a second, some mosquitoes 600 times, and a tiny gnat 1,000 times?",
    "A fly can react to something it sees and change direction in 30 milliseconds?",
    "Biologists have discovered that cockroaches can change course as many as 25 times in one second, making them the most nimble animals known?",
    "The American lobster can move through the water at a rate of up to 25 feet a second?",
    "The Pacific equatorial countercurrent flows eastward toward South America, carrying up to 40 million tons of warm water with it every second?",
    "The sound of thunder travels about 335 meters per second?" ,
    "A space vehicle must move at a rate of at least 11 kilometers per second to escape earth's gravitational pull?",
    "Some neutron stars spin 600 times a second, which is as fast as a dentist's drill?",
    "If you attempted to count the stars in a galaxy at a rate of one every second, it would take around 3,000 years to count them all?",
    "The sun burns 9 million tons of gas a second. At this rate, it has been estimated it will burn out in another 10 billion years?",
    "In one second 6,242,000,000,000,000,000 electrons pass any given point in an electrical current?",
    "Around 23,000,000,000 tonnes of CO2 are spewed into the Earth’s atmosphere every year. That's more than 700 tonnes every second?"
]
